name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm i

    - name: Run tests
      run: npm test
      
    - name: Build and package
      run: npm run build
      
    - name: Publish coverage report 
      uses: actions/upload-artifact@v2 
      with: 
        name: coverage-report 
        path: coverage
